fig = plt.figure()
    ax = fig.add_subplot(111)
    ax.set_title(f"{M}dimension")
    ax.plot(test_x, test_y, linestyle="solid", label="true function", color="red")
    ax.plot(test_x, pred_y_mu, linestyle="solid", color="blue")
    ax.plot(test_x, pred_y_mu - pred_y_sigma, linestyle="dashed", color="blue")
    ax.plot(test_x, pred_y_mu + pred_y_sigma, linestyle="dashed", color="blue")
    ax.legend()
    plt.show()